/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_ATTRIBUTES_GETMSG_PB_H_INCLUDED
#define PB_ATTRIBUTES_GETMSG_PB_H_INCLUDED
#include <pb1.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _attributes_getMsg { 
    uint32_t type; /* ctrl,set,get,clr,payload,ota */
    uint32_t s0; 
    uint32_t b0; 
    uint32_t s1; 
    uint32_t b1; 
    uint32_t s2; 
    uint32_t b2; 
    uint32_t s3; 
    uint32_t b3; 
    uint32_t s4; 
    uint32_t b4; 
    uint32_t s5; 
    uint32_t b5; 
    uint32_t mode; 
    char baddr[33]; 
    uint32_t bport; 
    uint32_t ping; 
    uint32_t pint; 
    uint32_t mload; 
    uint32_t nload; 
    uint32_t vmin; 
    uint32_t vmax; 
    uint32_t imin; 
    uint32_t imax; 
    uint32_t wmin; 
    uint32_t wmax; 
    uint32_t pmin; 
    uint32_t pmax; 
    uint32_t lamp; 
    uint32_t bri; 
    uint32_t timer; 
    char board[33]; 
    uint32_t mpc; 
    uint32_t verInt; 
    char verStr[33]; 
    char iccid[33]; 
    char apn[33]; 
    char imsiNumber[33]; 
    uint32_t lmin; 
    uint32_t lmax; 
    double astroLatitude; 
    double astroLongitude; 
    uint32_t astroSlot_on; 
    uint32_t astroSlot_off; 
    int32_t astroOnOffSet; 
    int32_t astroOffOffSet; 
} attributes_getMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define attributes_getMsg_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0}
#define attributes_getMsg_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define attributes_getMsg_type_tag               1
#define attributes_getMsg_s0_tag                 2
#define attributes_getMsg_b0_tag                 3
#define attributes_getMsg_s1_tag                 4
#define attributes_getMsg_b1_tag                 5
#define attributes_getMsg_s2_tag                 6
#define attributes_getMsg_b2_tag                 7
#define attributes_getMsg_s3_tag                 8
#define attributes_getMsg_b3_tag                 9
#define attributes_getMsg_s4_tag                 10
#define attributes_getMsg_b4_tag                 11
#define attributes_getMsg_s5_tag                 12
#define attributes_getMsg_b5_tag                 13
#define attributes_getMsg_mode_tag               14
#define attributes_getMsg_baddr_tag              15
#define attributes_getMsg_bport_tag              16
#define attributes_getMsg_ping_tag               17
#define attributes_getMsg_pint_tag               18
#define attributes_getMsg_mload_tag              19
#define attributes_getMsg_nload_tag              20
#define attributes_getMsg_vmin_tag               21
#define attributes_getMsg_vmax_tag               22
#define attributes_getMsg_imin_tag               23
#define attributes_getMsg_imax_tag               24
#define attributes_getMsg_wmin_tag               25
#define attributes_getMsg_wmax_tag               26
#define attributes_getMsg_pmin_tag               27
#define attributes_getMsg_pmax_tag               28
#define attributes_getMsg_lamp_tag               29
#define attributes_getMsg_bri_tag                30
#define attributes_getMsg_timer_tag              31
#define attributes_getMsg_board_tag              32
#define attributes_getMsg_mpc_tag                33
#define attributes_getMsg_verInt_tag             34
#define attributes_getMsg_verStr_tag             35
#define attributes_getMsg_iccid_tag              36
#define attributes_getMsg_apn_tag                37
#define attributes_getMsg_imsiNumber_tag         38
#define attributes_getMsg_lmin_tag               39
#define attributes_getMsg_lmax_tag               40
#define attributes_getMsg_astroLatitude_tag      41
#define attributes_getMsg_astroLongitude_tag     42
#define attributes_getMsg_astroSlot_on_tag       43
#define attributes_getMsg_astroSlot_off_tag      44
#define attributes_getMsg_astroOnOffSet_tag      45
#define attributes_getMsg_astroOffOffSet_tag     46

/* Struct field encoding specification for nanopb */
#define attributes_getMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   s0,                2) \
X(a, STATIC,   SINGULAR, UINT32,   b0,                3) \
X(a, STATIC,   SINGULAR, UINT32,   s1,                4) \
X(a, STATIC,   SINGULAR, UINT32,   b1,                5) \
X(a, STATIC,   SINGULAR, UINT32,   s2,                6) \
X(a, STATIC,   SINGULAR, UINT32,   b2,                7) \
X(a, STATIC,   SINGULAR, UINT32,   s3,                8) \
X(a, STATIC,   SINGULAR, UINT32,   b3,                9) \
X(a, STATIC,   SINGULAR, UINT32,   s4,               10) \
X(a, STATIC,   SINGULAR, UINT32,   b4,               11) \
X(a, STATIC,   SINGULAR, UINT32,   s5,               12) \
X(a, STATIC,   SINGULAR, UINT32,   b5,               13) \
X(a, STATIC,   SINGULAR, UINT32,   mode,             14) \
X(a, STATIC,   SINGULAR, STRING,   baddr,            15) \
X(a, STATIC,   SINGULAR, UINT32,   bport,            16) \
X(a, STATIC,   SINGULAR, UINT32,   ping,             17) \
X(a, STATIC,   SINGULAR, UINT32,   pint,             18) \
X(a, STATIC,   SINGULAR, UINT32,   mload,            19) \
X(a, STATIC,   SINGULAR, UINT32,   nload,            20) \
X(a, STATIC,   SINGULAR, UINT32,   vmin,             21) \
X(a, STATIC,   SINGULAR, UINT32,   vmax,             22) \
X(a, STATIC,   SINGULAR, UINT32,   imin,             23) \
X(a, STATIC,   SINGULAR, UINT32,   imax,             24) \
X(a, STATIC,   SINGULAR, UINT32,   wmin,             25) \
X(a, STATIC,   SINGULAR, UINT32,   wmax,             26) \
X(a, STATIC,   SINGULAR, UINT32,   pmin,             27) \
X(a, STATIC,   SINGULAR, UINT32,   pmax,             28) \
X(a, STATIC,   SINGULAR, UINT32,   lamp,             29) \
X(a, STATIC,   SINGULAR, UINT32,   bri,              30) \
X(a, STATIC,   SINGULAR, UINT32,   timer,            31) \
X(a, STATIC,   SINGULAR, STRING,   board,            32) \
X(a, STATIC,   SINGULAR, UINT32,   mpc,              33) \
X(a, STATIC,   SINGULAR, UINT32,   verInt,           34) \
X(a, STATIC,   SINGULAR, STRING,   verStr,           35) \
X(a, STATIC,   SINGULAR, STRING,   iccid,            36) \
X(a, STATIC,   SINGULAR, STRING,   apn,              37) \
X(a, STATIC,   SINGULAR, STRING,   imsiNumber,       38) \
X(a, STATIC,   SINGULAR, UINT32,   lmin,             39) \
X(a, STATIC,   SINGULAR, UINT32,   lmax,             40) \
X(a, STATIC,   SINGULAR, DOUBLE,   astroLatitude,    41) \
X(a, STATIC,   SINGULAR, DOUBLE,   astroLongitude,   42) \
X(a, STATIC,   SINGULAR, UINT32,   astroSlot_on,     43) \
X(a, STATIC,   SINGULAR, UINT32,   astroSlot_off,    44) \
X(a, STATIC,   SINGULAR, INT32,    astroOnOffSet,    45) \
X(a, STATIC,   SINGULAR, INT32,    astroOffOffSet,   46)
#define attributes_getMsg_CALLBACK NULL
#define attributes_getMsg_DEFAULT NULL

extern const pb_msgdesc_t attributes_getMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define attributes_getMsg_fields &attributes_getMsg_msg

/* Maximum encoded size of messages (where known) */
#define attributes_getMsg_size                   491

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
