/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_RPC_RPCNEW_PB_H_INCLUDED
#define PB_RPC_RPCNEW_PB_H_INCLUDED
#include <pb1.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rpc_RpcRequestMsg_Params { 
    int32_t rpcType; 
    uint32_t value; 
    uint32_t mode; 
    uint32_t lamp; 
    uint32_t timer; 
    uint32_t bri; 
    uint32_t from; 
    uint32_t to; 
    uint32_t pkt; 
    uint32_t version; 
    uint32_t s0; 
    uint32_t b0; 
    uint32_t s1; 
    uint32_t b1; 
    uint32_t s2; 
    uint32_t b2; 
    uint32_t s3; 
    uint32_t b3; 
    uint32_t s4; 
    uint32_t b4; 
    uint32_t s5; 
    uint32_t b5; 
    char baddr[33]; 
    uint32_t bport; 
    uint32_t ping; 
    uint32_t pint; 
    uint32_t mpc; 
    uint32_t ts; 
    uint32_t mload; 
    uint32_t nload; 
    uint32_t vmin; 
    uint32_t vmax; 
    uint32_t imin; 
    uint32_t imax; 
    uint32_t wmin; 
    uint32_t wmax; 
    uint32_t pmin; 
    uint32_t pmax; 
    char board[33]; 
    char apn[33]; 
    uint32_t lmin; 
    uint32_t lmax; 
    double astroLatitude; 
    double astroLongitude; 
    int32_t astroOnOffSet; 
    int32_t astroOffOffSet; 
} rpc_RpcRequestMsg_Params;

typedef struct _rpc_RpcRequestMsg { 
    char method[33]; 
    int32_t requestId; 
    bool has_params;
    rpc_RpcRequestMsg_Params params; 
} rpc_RpcRequestMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rpc_RpcRequestMsg_init_default           {"", 0, false, rpc_RpcRequestMsg_Params_init_default}
#define rpc_RpcRequestMsg_Params_init_default    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0, 0, 0, 0, 0, 0}
#define rpc_RpcRequestMsg_init_zero              {"", 0, false, rpc_RpcRequestMsg_Params_init_zero}
#define rpc_RpcRequestMsg_Params_init_zero       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rpc_RpcRequestMsg_Params_rpcType_tag     1
#define rpc_RpcRequestMsg_Params_value_tag       2
#define rpc_RpcRequestMsg_Params_mode_tag        3
#define rpc_RpcRequestMsg_Params_lamp_tag        4
#define rpc_RpcRequestMsg_Params_timer_tag       5
#define rpc_RpcRequestMsg_Params_bri_tag         6
#define rpc_RpcRequestMsg_Params_from_tag        7
#define rpc_RpcRequestMsg_Params_to_tag          8
#define rpc_RpcRequestMsg_Params_pkt_tag         9
#define rpc_RpcRequestMsg_Params_version_tag     10
#define rpc_RpcRequestMsg_Params_s0_tag          11
#define rpc_RpcRequestMsg_Params_b0_tag          12
#define rpc_RpcRequestMsg_Params_s1_tag          13
#define rpc_RpcRequestMsg_Params_b1_tag          14
#define rpc_RpcRequestMsg_Params_s2_tag          15
#define rpc_RpcRequestMsg_Params_b2_tag          16
#define rpc_RpcRequestMsg_Params_s3_tag          17
#define rpc_RpcRequestMsg_Params_b3_tag          18
#define rpc_RpcRequestMsg_Params_s4_tag          19
#define rpc_RpcRequestMsg_Params_b4_tag          20
#define rpc_RpcRequestMsg_Params_s5_tag          21
#define rpc_RpcRequestMsg_Params_b5_tag          22
#define rpc_RpcRequestMsg_Params_baddr_tag       23
#define rpc_RpcRequestMsg_Params_bport_tag       24
#define rpc_RpcRequestMsg_Params_ping_tag        25
#define rpc_RpcRequestMsg_Params_pint_tag        26
#define rpc_RpcRequestMsg_Params_mpc_tag         27
#define rpc_RpcRequestMsg_Params_ts_tag          28
#define rpc_RpcRequestMsg_Params_mload_tag       29
#define rpc_RpcRequestMsg_Params_nload_tag       30
#define rpc_RpcRequestMsg_Params_vmin_tag        31
#define rpc_RpcRequestMsg_Params_vmax_tag        32
#define rpc_RpcRequestMsg_Params_imin_tag        33
#define rpc_RpcRequestMsg_Params_imax_tag        34
#define rpc_RpcRequestMsg_Params_wmin_tag        35
#define rpc_RpcRequestMsg_Params_wmax_tag        36
#define rpc_RpcRequestMsg_Params_pmin_tag        37
#define rpc_RpcRequestMsg_Params_pmax_tag        38
#define rpc_RpcRequestMsg_Params_board_tag       39
#define rpc_RpcRequestMsg_Params_apn_tag         40
#define rpc_RpcRequestMsg_Params_lmin_tag        41
#define rpc_RpcRequestMsg_Params_lmax_tag        42
#define rpc_RpcRequestMsg_Params_astroLatitude_tag 43
#define rpc_RpcRequestMsg_Params_astroLongitude_tag 44
#define rpc_RpcRequestMsg_Params_astroOnOffSet_tag 45
#define rpc_RpcRequestMsg_Params_astroOffOffSet_tag 46
#define rpc_RpcRequestMsg_method_tag             1
#define rpc_RpcRequestMsg_requestId_tag          2
#define rpc_RpcRequestMsg_params_tag             3

/* Struct field encoding specification for nanopb */
#define rpc_RpcRequestMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   method,            1) \
X(a, STATIC,   SINGULAR, INT32,    requestId,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            3)
#define rpc_RpcRequestMsg_CALLBACK NULL
#define rpc_RpcRequestMsg_DEFAULT NULL
#define rpc_RpcRequestMsg_params_MSGTYPE rpc_RpcRequestMsg_Params

#define rpc_RpcRequestMsg_Params_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    rpcType,           1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              3) \
X(a, STATIC,   SINGULAR, UINT32,   lamp,              4) \
X(a, STATIC,   SINGULAR, UINT32,   timer,             5) \
X(a, STATIC,   SINGULAR, UINT32,   bri,               6) \
X(a, STATIC,   SINGULAR, UINT32,   from,              7) \
X(a, STATIC,   SINGULAR, UINT32,   to,                8) \
X(a, STATIC,   SINGULAR, UINT32,   pkt,               9) \
X(a, STATIC,   SINGULAR, UINT32,   version,          10) \
X(a, STATIC,   SINGULAR, UINT32,   s0,               11) \
X(a, STATIC,   SINGULAR, UINT32,   b0,               12) \
X(a, STATIC,   SINGULAR, UINT32,   s1,               13) \
X(a, STATIC,   SINGULAR, UINT32,   b1,               14) \
X(a, STATIC,   SINGULAR, UINT32,   s2,               15) \
X(a, STATIC,   SINGULAR, UINT32,   b2,               16) \
X(a, STATIC,   SINGULAR, UINT32,   s3,               17) \
X(a, STATIC,   SINGULAR, UINT32,   b3,               18) \
X(a, STATIC,   SINGULAR, UINT32,   s4,               19) \
X(a, STATIC,   SINGULAR, UINT32,   b4,               20) \
X(a, STATIC,   SINGULAR, UINT32,   s5,               21) \
X(a, STATIC,   SINGULAR, UINT32,   b5,               22) \
X(a, STATIC,   SINGULAR, STRING,   baddr,            23) \
X(a, STATIC,   SINGULAR, UINT32,   bport,            24) \
X(a, STATIC,   SINGULAR, UINT32,   ping,             25) \
X(a, STATIC,   SINGULAR, UINT32,   pint,             26) \
X(a, STATIC,   SINGULAR, UINT32,   mpc,              27) \
X(a, STATIC,   SINGULAR, UINT32,   ts,               28) \
X(a, STATIC,   SINGULAR, UINT32,   mload,            29) \
X(a, STATIC,   SINGULAR, UINT32,   nload,            30) \
X(a, STATIC,   SINGULAR, UINT32,   vmin,             31) \
X(a, STATIC,   SINGULAR, UINT32,   vmax,             32) \
X(a, STATIC,   SINGULAR, UINT32,   imin,             33) \
X(a, STATIC,   SINGULAR, UINT32,   imax,             34) \
X(a, STATIC,   SINGULAR, UINT32,   wmin,             35) \
X(a, STATIC,   SINGULAR, UINT32,   wmax,             36) \
X(a, STATIC,   SINGULAR, UINT32,   pmin,             37) \
X(a, STATIC,   SINGULAR, UINT32,   pmax,             38) \
X(a, STATIC,   SINGULAR, STRING,   board,            39) \
X(a, STATIC,   SINGULAR, STRING,   apn,              40) \
X(a, STATIC,   SINGULAR, UINT32,   lmin,             41) \
X(a, STATIC,   SINGULAR, UINT32,   lmax,             42) \
X(a, STATIC,   SINGULAR, DOUBLE,   astroLatitude,    43) \
X(a, STATIC,   SINGULAR, DOUBLE,   astroLongitude,   44) \
X(a, STATIC,   SINGULAR, INT32,    astroOnOffSet,    45) \
X(a, STATIC,   SINGULAR, INT32,    astroOffOffSet,   46)
#define rpc_RpcRequestMsg_Params_CALLBACK NULL
#define rpc_RpcRequestMsg_Params_DEFAULT NULL

extern const pb_msgdesc_t rpc_RpcRequestMsg_msg;
extern const pb_msgdesc_t rpc_RpcRequestMsg_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rpc_RpcRequestMsg_fields &rpc_RpcRequestMsg_msg
#define rpc_RpcRequestMsg_Params_fields &rpc_RpcRequestMsg_Params_msg

/* Maximum encoded size of messages (where known) */
#define rpc_RpcRequestMsg_Params_size            412
#define rpc_RpcRequestMsg_size                   460

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
