/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#include <pb1.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _telemetry_Telemetry_Values { 
    uint32_t pkt; 
    uint32_t mode; 
    uint32_t rly; 
    uint32_t lmp; 
    uint32_t bri; 
    uint32_t a0; 
    uint32_t ri; 
    uint32_t rv; 
    int32_t rpf;
    uint32_t rw; 
    uint64_t wh; 
    uint32_t rbt; 
    uint32_t fc; 
    uint32_t fd; 
    uint32_t pwrf; 
    uint32_t pwrr; 
    char rot[17]; 
    int32_t ctp; 
    uint32_t rnk; 
    int32_t sig; 
    uint32_t otaPercentage; 
    uint32_t presentGridStatus;
    uint32_t coControllerStatus;
    char version[17];
    float latitude;
    float longitude;
    float altitude;
    uint32_t gnssFix;
    uint32_t satellite;
    float hdop;
} telemetry_Telemetry_Values;

typedef struct _telemetry_Telemetry { 
    int64_t ts; 
    bool has_values;
    telemetry_Telemetry_Values values; 
} telemetry_Telemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define telemetry_Telemetry_init_default         {0, false, telemetry_Telemetry_Values_init_default}
#define telemetry_Telemetry_Values_init_default  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0}
#define telemetry_Telemetry_init_zero            {0, false, telemetry_Telemetry_Values_init_zero}
#define telemetry_Telemetry_Values_init_zero     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define telemetry_Telemetry_Values_pkt_tag       1
#define telemetry_Telemetry_Values_mode_tag      2
#define telemetry_Telemetry_Values_rly_tag       3
#define telemetry_Telemetry_Values_lmp_tag       4
#define telemetry_Telemetry_Values_bri_tag       5
#define telemetry_Telemetry_Values_a0_tag        6
#define telemetry_Telemetry_Values_ri_tag        7
#define telemetry_Telemetry_Values_rv_tag        8
#define telemetry_Telemetry_Values_rpf_tag       9
#define telemetry_Telemetry_Values_rw_tag        10
#define telemetry_Telemetry_Values_wh_tag        11
#define telemetry_Telemetry_Values_rbt_tag       12
#define telemetry_Telemetry_Values_fc_tag        13
#define telemetry_Telemetry_Values_fd_tag        14
#define telemetry_Telemetry_Values_pwrf_tag      15
#define telemetry_Telemetry_Values_pwrr_tag      16
#define telemetry_Telemetry_Values_rot_tag       17
#define telemetry_Telemetry_Values_ctp_tag       18
#define telemetry_Telemetry_Values_rnk_tag       19
#define telemetry_Telemetry_Values_sig_tag       20
#define telemetry_Telemetry_Values_otaPercentage_tag 21
#define telemetry_Telemetry_Values_presentGridStatus_tag 22
#define telemetry_Telemetry_Values_coControllerStatus_tag 23
#define telemetry_Telemetry_Values_version_tag   24
#define telemetry_Telemetry_Values_latitude_tag  25
#define telemetry_Telemetry_Values_longitude_tag 26
#define telemetry_Telemetry_Values_altitude_tag  27
#define telemetry_Telemetry_Values_gnssFix_tag   28
#define telemetry_Telemetry_Values_satellite_tag 29
#define telemetry_Telemetry_Values_hdop_tag      30
#define telemetry_Telemetry_ts_tag               1
#define telemetry_Telemetry_values_tag           2

/* Struct field encoding specification for nanopb */
#define telemetry_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    ts,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  values,            2)
#define telemetry_Telemetry_CALLBACK NULL
#define telemetry_Telemetry_DEFAULT NULL
#define telemetry_Telemetry_values_MSGTYPE telemetry_Telemetry_Values

#define telemetry_Telemetry_Values_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pkt,               1) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              2) \
X(a, STATIC,   SINGULAR, UINT32,   rly,               3) \
X(a, STATIC,   SINGULAR, UINT32,   lmp,               4) \
X(a, STATIC,   SINGULAR, UINT32,   bri,               5) \
X(a, STATIC,   SINGULAR, UINT32,   a0,                6) \
X(a, STATIC,   SINGULAR, UINT32,   ri,                7) \
X(a, STATIC,   SINGULAR, UINT32,   rv,                8) \
X(a, STATIC,   SINGULAR, INT32,    rpf,               9) \
X(a, STATIC,   SINGULAR, UINT32,   rw,               10) \
X(a, STATIC,   SINGULAR, UINT64,   wh,               11) \
X(a, STATIC,   SINGULAR, UINT32,   rbt,              12) \
X(a, STATIC,   SINGULAR, UINT32,   fc,               13) \
X(a, STATIC,   SINGULAR, UINT32,   fd,               14) \
X(a, STATIC,   SINGULAR, UINT32,   pwrf,             15) \
X(a, STATIC,   SINGULAR, UINT32,   pwrr,             16) \
X(a, STATIC,   SINGULAR, STRING,   rot,              17) \
X(a, STATIC,   SINGULAR, INT32,    ctp,              18) \
X(a, STATIC,   SINGULAR, UINT32,   rnk,              19) \
X(a, STATIC,   SINGULAR, INT32,    sig,              20) \
X(a, STATIC,   SINGULAR, UINT32,   otaPercentage,    21) \
X(a, STATIC,   SINGULAR, UINT32,   presentGridStatus,  22) \
X(a, STATIC,   SINGULAR, UINT32,   coControllerStatus,  23) \
X(a, STATIC,   SINGULAR, STRING,   version,          24) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,         25) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,        26) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,         27) \
X(a, STATIC,   SINGULAR, UINT32,   gnssFix,          28) \
X(a, STATIC,   SINGULAR, UINT32,   satellite,        29) \
X(a, STATIC,   SINGULAR, FLOAT,    hdop,             30)
#define telemetry_Telemetry_Values_CALLBACK NULL
#define telemetry_Telemetry_Values_DEFAULT NULL

extern const pb_msgdesc_t telemetry_Telemetry_msg;
extern const pb_msgdesc_t telemetry_Telemetry_Values_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define telemetry_Telemetry_fields &telemetry_Telemetry_msg
#define telemetry_Telemetry_Values_fields &telemetry_Telemetry_Values_msg

/* Maximum encoded size of messages (where known) */
#define telemetry_Telemetry_Values_size          235
#define telemetry_Telemetry_size                 249

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
